version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: epic_backend_template_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: epic_backend_template_db
    ports:
      - '5555:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
